/**
 * Direct (tree-shakeable) imports for the ~30 lucide icons the component UI
 * resolves by semantic name. Emitting them as direct imports (instead of
 * reading them out of the 1,700-entry `lucideIconMap` at runtime) means any
 * consumer using the built-in semantic icons never pulls the full catalog -
 * the full map is only loaded lazily for arbitrary lucide names
 * ("heart", ...). See registry.tsx.
 *
 * This file is the source of truth for the semantic-name -> lucide-component
 * mapping. It is maintained by hand and validated by the drift guard in
 * scripts/gen-icon-map.mjs, which fails (in both generate and --check mode)
 * if any import below was renamed or deprecated in the installed lucide-react:
 *
 *   node scripts/gen-icon-map.mjs --check
 */
import {
  Settings,
  LogOut,
  ChevronDown,
  Search,
  Check,
  Moon,
  Sun,
  Bell,
  Menu,
  ChevronLeft,
  ChevronRight,
  Calendar,
  ArrowRight,
  Sparkles,
  BookOpen,
  Building,
  Users,
  Shield,
  CreditCard,
  LayoutDashboard,
  FileText,
  CircleQuestionMark,
  LayoutGrid,
  List,
  TriangleAlert,
  Copy,
  ChevronsUpDown,
  ChevronsUp,
  ChevronsDown,
  Eye,
  EyeOff,
  Compass,
  Layers,
  Palette,
  KeyRound,
  User,
  Upload,
  QrCode,
  Trash,
  Minus,
  Plus,
  GripHorizontal,
  GripVertical,
  Ellipsis,
  EllipsisVertical,
} from "lucide-react";
import type { IconComponent } from "./registry.js";

export const SEMANTIC_ICONS: Partial<Record<string, IconComponent>> = {
  settings: Settings,
  logout: LogOut,
  "chevron-down": ChevronDown,
  search: Search,
  check: Check,
  moon: Moon,
  sun: Sun,
  bell: Bell,
  menu: Menu,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  calendar: Calendar,
  "arrow-right": ArrowRight,
  sparkles: Sparkles,
  "book-open": BookOpen,
  building: Building,
  users: Users,
  shield: Shield,
  "credit-card": CreditCard,
  dashboard: LayoutDashboard,
  document: FileText,
  help: CircleQuestionMark,
  grid: LayoutGrid,
  list: List,
  "triangle-alert": TriangleAlert,
  copy: Copy,
  "chevron-up-down": ChevronsUpDown,
  "chevrons-up": ChevronsUp,
  "chevrons-down": ChevronsDown,
  "more-horizontal": Ellipsis,
  "more-vertical": EllipsisVertical,
  eye: Eye,
  "eye-off": EyeOff,
  compass: Compass,
  layers: Layers,
  palette: Palette,
  "key-round": KeyRound,
  user: User,
  upload: Upload,
  qrcode: QrCode,
  trash: Trash,
  minus: Minus,
  plus: Plus,
  "grip-horizontal": GripHorizontal,
  "grip-vertical": GripVertical,
  ellipsis: Ellipsis,
};
