/**
 * Full ISO 3166-1 country dial-code dataset with region metadata.
 * Sorted alphabetically by display name within each region.
 */

export type CountryRegion =
  | "africa"
  | "asia"
  | "caribbean"
  | "europe"
  | "middle-east"
  | "north-america"
  | "oceania"
  | "south-america";

export const COUNTRY_REGION_LABELS: Record<CountryRegion, string> = {
  africa: "Africa",
  asia: "Asia",
  caribbean: "Caribbean",
  europe: "Europe",
  "middle-east": "Middle East",
  "north-america": "North America",
  oceania: "Oceania",
  "south-america": "South America",
};

export interface CountryCodeData {
  /** ISO 3166-1 alpha-2 code, e.g. "NG". */
  country: string;
  /** Dial code with leading "+", e.g. "+234". */
  code: string;
  /** English display name. */
  name: string;
  /** World region used for filtering/grouping. */
  region: CountryRegion;
}

/** Every ISO 3166-1 entry with an ITU dial code, incl. common territories. */
export const ALL_COUNTRY_CODES: CountryCodeData[] = [
  /* ── Africa ─────────────────────────────────────────────── */
  { country: "DZ", code: "+213", name: "Algeria", region: "africa" },
  { country: "AO", code: "+244", name: "Angola", region: "africa" },
  { country: "BJ", code: "+229", name: "Benin", region: "africa" },
  { country: "BW", code: "+267", name: "Botswana", region: "africa" },
  { country: "BF", code: "+226", name: "Burkina Faso", region: "africa" },
  { country: "BI", code: "+257", name: "Burundi", region: "africa" },
  { country: "CV", code: "+238", name: "Cabo Verde", region: "africa" },
  { country: "CM", code: "+237", name: "Cameroon", region: "africa" },
  {
    country: "CF",
    code: "+236",
    name: "Central African Republic",
    region: "africa",
  },
  { country: "TD", code: "+235", name: "Chad", region: "africa" },
  { country: "KM", code: "+269", name: "Comoros", region: "africa" },
  { country: "CG", code: "+242", name: "Congo", region: "africa" },
  { country: "CD", code: "+243", name: "Congo (DRC)", region: "africa" },
  { country: "CI", code: "+225", name: "Côte d'Ivoire", region: "africa" },
  { country: "DJ", code: "+253", name: "Djibouti", region: "africa" },
  { country: "EG", code: "+20", name: "Egypt", region: "africa" },
  { country: "GQ", code: "+240", name: "Equatorial Guinea", region: "africa" },
  { country: "ER", code: "+291", name: "Eritrea", region: "africa" },
  { country: "SZ", code: "+268", name: "Eswatini", region: "africa" },
  { country: "ET", code: "+251", name: "Ethiopia", region: "africa" },
  { country: "GA", code: "+241", name: "Gabon", region: "africa" },
  { country: "GM", code: "+220", name: "Gambia", region: "africa" },
  { country: "GH", code: "+233", name: "Ghana", region: "africa" },
  { country: "GN", code: "+224", name: "Guinea", region: "africa" },
  { country: "GW", code: "+245", name: "Guinea-Bissau", region: "africa" },
  { country: "KE", code: "+254", name: "Kenya", region: "africa" },
  { country: "LS", code: "+266", name: "Lesotho", region: "africa" },
  { country: "LR", code: "+231", name: "Liberia", region: "africa" },
  { country: "LY", code: "+218", name: "Libya", region: "africa" },
  { country: "MG", code: "+261", name: "Madagascar", region: "africa" },
  { country: "MW", code: "+265", name: "Malawi", region: "africa" },
  { country: "ML", code: "+223", name: "Mali", region: "africa" },
  { country: "MR", code: "+222", name: "Mauritania", region: "africa" },
  { country: "MU", code: "+230", name: "Mauritius", region: "africa" },
  { country: "YT", code: "+262", name: "Mayotte", region: "africa" },
  { country: "MA", code: "+212", name: "Morocco", region: "africa" },
  { country: "MZ", code: "+258", name: "Mozambique", region: "africa" },
  { country: "NA", code: "+264", name: "Namibia", region: "africa" },
  { country: "NE", code: "+227", name: "Niger", region: "africa" },
  { country: "NG", code: "+234", name: "Nigeria", region: "africa" },
  { country: "RE", code: "+262", name: "Réunion", region: "africa" },
  { country: "RW", code: "+250", name: "Rwanda", region: "africa" },
  { country: "SH", code: "+290", name: "Saint Helena", region: "africa" },
  {
    country: "ST",
    code: "+239",
    name: "São Tomé and Príncipe",
    region: "africa",
  },
  { country: "SN", code: "+221", name: "Senegal", region: "africa" },
  { country: "SC", code: "+248", name: "Seychelles", region: "africa" },
  { country: "SL", code: "+232", name: "Sierra Leone", region: "africa" },
  { country: "SO", code: "+252", name: "Somalia", region: "africa" },
  { country: "ZA", code: "+27", name: "South Africa", region: "africa" },
  { country: "SS", code: "+211", name: "South Sudan", region: "africa" },
  { country: "SD", code: "+249", name: "Sudan", region: "africa" },
  { country: "TZ", code: "+255", name: "Tanzania", region: "africa" },
  { country: "TG", code: "+228", name: "Togo", region: "africa" },
  { country: "TN", code: "+216", name: "Tunisia", region: "africa" },
  { country: "UG", code: "+256", name: "Uganda", region: "africa" },
  { country: "EH", code: "+212", name: "Western Sahara", region: "africa" },
  { country: "ZM", code: "+260", name: "Zambia", region: "africa" },
  { country: "ZW", code: "+263", name: "Zimbabwe", region: "africa" },

  /* ── Asia ───────────────────────────────────────────────── */
  { country: "AF", code: "+93", name: "Afghanistan", region: "asia" },
  { country: "AM", code: "+374", name: "Armenia", region: "asia" },
  { country: "AZ", code: "+994", name: "Azerbaijan", region: "asia" },
  { country: "BD", code: "+880", name: "Bangladesh", region: "asia" },
  { country: "BT", code: "+975", name: "Bhutan", region: "asia" },
  { country: "BN", code: "+673", name: "Brunei", region: "asia" },
  { country: "KH", code: "+855", name: "Cambodia", region: "asia" },
  { country: "CN", code: "+86", name: "China", region: "asia" },
  { country: "GE", code: "+995", name: "Georgia", region: "asia" },
  { country: "HK", code: "+852", name: "Hong Kong", region: "asia" },
  { country: "IN", code: "+91", name: "India", region: "asia" },
  { country: "ID", code: "+62", name: "Indonesia", region: "asia" },
  { country: "JP", code: "+81", name: "Japan", region: "asia" },
  { country: "KZ", code: "+7", name: "Kazakhstan", region: "asia" },
  { country: "KP", code: "+850", name: "North Korea", region: "asia" },
  { country: "KR", code: "+82", name: "South Korea", region: "asia" },
  { country: "KG", code: "+996", name: "Kyrgyzstan", region: "asia" },
  { country: "LA", code: "+856", name: "Laos", region: "asia" },
  { country: "MO", code: "+853", name: "Macau", region: "asia" },
  { country: "MY", code: "+60", name: "Malaysia", region: "asia" },
  { country: "MV", code: "+960", name: "Maldives", region: "asia" },
  { country: "MN", code: "+976", name: "Mongolia", region: "asia" },
  { country: "MM", code: "+95", name: "Myanmar", region: "asia" },
  { country: "NP", code: "+977", name: "Nepal", region: "asia" },
  { country: "PK", code: "+92", name: "Pakistan", region: "asia" },
  { country: "PH", code: "+63", name: "Philippines", region: "asia" },
  { country: "SG", code: "+65", name: "Singapore", region: "asia" },
  { country: "LK", code: "+94", name: "Sri Lanka", region: "asia" },
  { country: "TW", code: "+886", name: "Taiwan", region: "asia" },
  { country: "TJ", code: "+992", name: "Tajikistan", region: "asia" },
  { country: "TH", code: "+66", name: "Thailand", region: "asia" },
  { country: "TL", code: "+670", name: "Timor-Leste", region: "asia" },
  { country: "TM", code: "+993", name: "Turkmenistan", region: "asia" },
  { country: "UZ", code: "+998", name: "Uzbekistan", region: "asia" },
  { country: "VN", code: "+84", name: "Vietnam", region: "asia" },

  /* ── Caribbean ──────────────────────────────────────────── */
  { country: "AI", code: "+1", name: "Anguilla", region: "caribbean" },
  {
    country: "AG",
    code: "+1",
    name: "Antigua and Barbuda",
    region: "caribbean",
  },
  { country: "AW", code: "+297", name: "Aruba", region: "caribbean" },
  { country: "BS", code: "+1", name: "Bahamas", region: "caribbean" },
  { country: "BB", code: "+1", name: "Barbados", region: "caribbean" },
  {
    country: "BQ",
    code: "+599",
    name: "Caribbean Netherlands",
    region: "caribbean",
  },
  { country: "KY", code: "+1", name: "Cayman Islands", region: "caribbean" },
  { country: "CU", code: "+53", name: "Cuba", region: "caribbean" },
  { country: "CW", code: "+599", name: "Curaçao", region: "caribbean" },
  { country: "DM", code: "+1", name: "Dominica", region: "caribbean" },
  {
    country: "DO",
    code: "+1",
    name: "Dominican Republic",
    region: "caribbean",
  },
  { country: "GD", code: "+1", name: "Grenada", region: "caribbean" },
  { country: "GP", code: "+590", name: "Guadeloupe", region: "caribbean" },
  { country: "HT", code: "+509", name: "Haiti", region: "caribbean" },
  { country: "JM", code: "+1", name: "Jamaica", region: "caribbean" },
  { country: "MQ", code: "+596", name: "Martinique", region: "caribbean" },
  { country: "MS", code: "+1", name: "Montserrat", region: "caribbean" },
  { country: "PR", code: "+1", name: "Puerto Rico", region: "caribbean" },
  {
    country: "BL",
    code: "+590",
    name: "Saint Barthélemy",
    region: "caribbean",
  },
  {
    country: "KN",
    code: "+1",
    name: "Saint Kitts and Nevis",
    region: "caribbean",
  },
  { country: "LC", code: "+1", name: "Saint Lucia", region: "caribbean" },
  { country: "MF", code: "+590", name: "Saint Martin", region: "caribbean" },
  { country: "VC", code: "+1", name: "Saint Vincent", region: "caribbean" },
  { country: "SX", code: "+1", name: "Sint Maarten", region: "caribbean" },
  {
    country: "TT",
    code: "+1",
    name: "Trinidad and Tobago",
    region: "caribbean",
  },
  {
    country: "TC",
    code: "+1",
    name: "Turks and Caicos Islands",
    region: "caribbean",
  },
  {
    country: "VG",
    code: "+1",
    name: "British Virgin Islands",
    region: "caribbean",
  },
  { country: "VI", code: "+1", name: "US Virgin Islands", region: "caribbean" },

  /* ── Europe ─────────────────────────────────────────────── */
  { country: "AX", code: "+358", name: "Åland Islands", region: "europe" },
  { country: "AL", code: "+355", name: "Albania", region: "europe" },
  { country: "AD", code: "+376", name: "Andorra", region: "europe" },
  { country: "AT", code: "+43", name: "Austria", region: "europe" },
  { country: "BY", code: "+375", name: "Belarus", region: "europe" },
  { country: "BE", code: "+32", name: "Belgium", region: "europe" },
  {
    country: "BA",
    code: "+387",
    name: "Bosnia and Herzegovina",
    region: "europe",
  },
  { country: "BG", code: "+359", name: "Bulgaria", region: "europe" },
  { country: "HR", code: "+385", name: "Croatia", region: "europe" },
  { country: "CY", code: "+357", name: "Cyprus", region: "europe" },
  { country: "CZ", code: "+420", name: "Czechia", region: "europe" },
  { country: "DK", code: "+45", name: "Denmark", region: "europe" },
  { country: "EE", code: "+372", name: "Estonia", region: "europe" },
  { country: "FO", code: "+298", name: "Faroe Islands", region: "europe" },
  { country: "FI", code: "+358", name: "Finland", region: "europe" },
  { country: "FR", code: "+33", name: "France", region: "europe" },
  { country: "DE", code: "+49", name: "Germany", region: "europe" },
  { country: "GI", code: "+350", name: "Gibraltar", region: "europe" },
  { country: "GR", code: "+30", name: "Greece", region: "europe" },
  { country: "GG", code: "+44", name: "Guernsey", region: "europe" },
  { country: "HU", code: "+36", name: "Hungary", region: "europe" },
  { country: "IS", code: "+354", name: "Iceland", region: "europe" },
  { country: "IE", code: "+353", name: "Ireland", region: "europe" },
  { country: "IM", code: "+44", name: "Isle of Man", region: "europe" },
  { country: "IT", code: "+39", name: "Italy", region: "europe" },
  { country: "JE", code: "+44", name: "Jersey", region: "europe" },
  { country: "LV", code: "+371", name: "Latvia", region: "europe" },
  { country: "LI", code: "+423", name: "Liechtenstein", region: "europe" },
  { country: "LT", code: "+370", name: "Lithuania", region: "europe" },
  { country: "LU", code: "+352", name: "Luxembourg", region: "europe" },
  { country: "MT", code: "+356", name: "Malta", region: "europe" },
  { country: "MD", code: "+373", name: "Moldova", region: "europe" },
  { country: "MC", code: "+377", name: "Monaco", region: "europe" },
  { country: "ME", code: "+382", name: "Montenegro", region: "europe" },
  { country: "NL", code: "+31", name: "Netherlands", region: "europe" },
  { country: "MK", code: "+389", name: "North Macedonia", region: "europe" },
  { country: "NO", code: "+47", name: "Norway", region: "europe" },
  { country: "PL", code: "+48", name: "Poland", region: "europe" },
  { country: "PT", code: "+351", name: "Portugal", region: "europe" },
  { country: "RO", code: "+40", name: "Romania", region: "europe" },
  { country: "RU", code: "+7", name: "Russia", region: "europe" },
  { country: "SM", code: "+378", name: "San Marino", region: "europe" },
  { country: "RS", code: "+381", name: "Serbia", region: "europe" },
  { country: "SK", code: "+421", name: "Slovakia", region: "europe" },
  { country: "SI", code: "+386", name: "Slovenia", region: "europe" },
  { country: "ES", code: "+34", name: "Spain", region: "europe" },
  {
    country: "SJ",
    code: "+47",
    name: "Svalbard and Jan Mayen",
    region: "europe",
  },
  { country: "SE", code: "+46", name: "Sweden", region: "europe" },
  { country: "CH", code: "+41", name: "Switzerland", region: "europe" },
  { country: "TR", code: "+90", name: "Turkey", region: "europe" },
  { country: "UA", code: "+380", name: "Ukraine", region: "europe" },
  { country: "GB", code: "+44", name: "United Kingdom", region: "europe" },
  { country: "VA", code: "+39", name: "Vatican City", region: "europe" },

  /* ── Middle East ────────────────────────────────────────── */
  { country: "BH", code: "+973", name: "Bahrain", region: "middle-east" },
  { country: "IR", code: "+98", name: "Iran", region: "middle-east" },
  { country: "IQ", code: "+964", name: "Iraq", region: "middle-east" },
  { country: "IL", code: "+972", name: "Israel", region: "middle-east" },
  { country: "JO", code: "+962", name: "Jordan", region: "middle-east" },
  { country: "KW", code: "+965", name: "Kuwait", region: "middle-east" },
  { country: "LB", code: "+961", name: "Lebanon", region: "middle-east" },
  { country: "OM", code: "+968", name: "Oman", region: "middle-east" },
  { country: "PS", code: "+970", name: "Palestine", region: "middle-east" },
  { country: "QA", code: "+974", name: "Qatar", region: "middle-east" },
  { country: "SA", code: "+966", name: "Saudi Arabia", region: "middle-east" },
  { country: "SY", code: "+963", name: "Syria", region: "middle-east" },
  {
    country: "AE",
    code: "+971",
    name: "United Arab Emirates",
    region: "middle-east",
  },
  { country: "YE", code: "+967", name: "Yemen", region: "middle-east" },

  /* ── North America ──────────────────────────────────────── */
  { country: "BM", code: "+1", name: "Bermuda", region: "north-america" },
  { country: "CA", code: "+1", name: "Canada", region: "north-america" },
  { country: "GL", code: "+299", name: "Greenland", region: "north-america" },
  { country: "MX", code: "+52", name: "Mexico", region: "north-america" },
  {
    country: "PM",
    code: "+508",
    name: "Saint Pierre and Miquelon",
    region: "north-america",
  },
  { country: "US", code: "+1", name: "United States", region: "north-america" },

  /* ── Oceania ────────────────────────────────────────────── */
  { country: "AS", code: "+1", name: "American Samoa", region: "oceania" },
  { country: "AU", code: "+61", name: "Australia", region: "oceania" },
  { country: "CK", code: "+682", name: "Cook Islands", region: "oceania" },
  { country: "FJ", code: "+679", name: "Fiji", region: "oceania" },
  { country: "PF", code: "+689", name: "French Polynesia", region: "oceania" },
  { country: "GU", code: "+1", name: "Guam", region: "oceania" },
  { country: "KI", code: "+686", name: "Kiribati", region: "oceania" },
  { country: "MH", code: "+692", name: "Marshall Islands", region: "oceania" },
  { country: "FM", code: "+691", name: "Micronesia", region: "oceania" },
  { country: "NR", code: "+674", name: "Nauru", region: "oceania" },
  { country: "NC", code: "+687", name: "New Caledonia", region: "oceania" },
  { country: "NZ", code: "+64", name: "New Zealand", region: "oceania" },
  { country: "NU", code: "+683", name: "Niue", region: "oceania" },
  { country: "PW", code: "+680", name: "Palau", region: "oceania" },
  { country: "PG", code: "+675", name: "Papua New Guinea", region: "oceania" },
  { country: "WS", code: "+685", name: "Samoa", region: "oceania" },
  { country: "SB", code: "+677", name: "Solomon Islands", region: "oceania" },
  { country: "TK", code: "+690", name: "Tokelau", region: "oceania" },
  { country: "TO", code: "+676", name: "Tonga", region: "oceania" },
  { country: "TV", code: "+688", name: "Tuvalu", region: "oceania" },
  { country: "VU", code: "+678", name: "Vanuatu", region: "oceania" },
  { country: "WF", code: "+681", name: "Wallis and Futuna", region: "oceania" },

  /* ── South America ──────────────────────────────────────── */
  { country: "AR", code: "+54", name: "Argentina", region: "south-america" },
  { country: "BO", code: "+591", name: "Bolivia", region: "south-america" },
  { country: "BR", code: "+55", name: "Brazil", region: "south-america" },
  { country: "CL", code: "+56", name: "Chile", region: "south-america" },
  { country: "CO", code: "+57", name: "Colombia", region: "south-america" },
  { country: "EC", code: "+593", name: "Ecuador", region: "south-america" },
  {
    country: "FK",
    code: "+500",
    name: "Falkland Islands",
    region: "south-america",
  },
  { country: "GY", code: "+592", name: "Guyana", region: "south-america" },
  { country: "PY", code: "+595", name: "Paraguay", region: "south-america" },
  { country: "PE", code: "+51", name: "Peru", region: "south-america" },
  { country: "SR", code: "+597", name: "Suriname", region: "south-america" },
  { country: "UY", code: "+598", name: "Uruguay", region: "south-america" },
  { country: "VE", code: "+58", name: "Venezuela", region: "south-america" },
];
