// AUTO-GENERATED by scripts/gen-changelog.mjs, do not edit by hand.
// Regenerate with: node scripts/gen-changelog.mjs
//
// Historical entries are curated in the generator. Pending entries are
// generated from .changeset/*.md files.

import type { ChangelogRelease } from "@fusorb/facet-components";

export const changelog: ChangelogRelease[] = [
  {
    "version": "2.0.0",
    "date": "2026-09-19",
    "tag": "release",
    "title": "2.0.0 - Facet workspace evolution",
    "changes": [
      {
        "kind": "added",
        "text": "New @fusorb/facet-motion package: declarative animation system"
      },
      {
        "kind": "added",
        "text": "Added @fusorb/facet-native package - the React Native motion driver for @fusorb/facet-motion. Re-exports motionValues from @fusorb/facet-tokens and provides: toEasingCurve (CSS easing var → native ..."
      },
      {
        "kind": "added",
        "text": "New @fusorb/facet-sandbox package: framework-agnostic live-preview host for"
      },
      {
        "kind": "added",
        "text": "Adds domain-customizable motion presets that mirror the auth/layout preset"
      },
      {
        "kind": "added",
        "text": "Add Pill component - a theme-adaptable, fully-rounded pill with a leading dot, icon, or custom indicator. Renders as a span by default, a button when selected or onClick is provided, or an anchor w..."
      },
      {
        "kind": "changed",
        "text": "Chart: add pie/donut/composed chart types, per-series type override, smooth & step curves, crosshair cursor, floating tooltip, stacked mode, animation, legend toggle, horizontal bars, bar grouping,..."
      },
      {
        "kind": "changed",
        "text": "Evolve the facet workspace."
      },
      {
        "kind": "changed",
        "text": "Motion tokens (CSS variables) added to :root in tokens.css"
      },
      {
        "kind": "changed",
        "text": "Removed unused tw-animate-css dependency after migration to facet-native animate-facet-* animation grammar. No component source or CSS bundle references it anymore."
      },
      {
        "kind": "fixed",
        "text": "Chart: fix 3 failing tests (handlePointerMove no longer bails on zero-width SVG rects in jsdom; ResizeObserver scaleRef formula corrected to width/rect.width)."
      },
      {
        "kind": "fixed",
        "text": "Chart v2 polish - crosshair fix, animations, and range selector"
      },
      {
        "kind": "fixed",
        "text": "Chart crosshair + dynamic axis range"
      },
      {
        "kind": "fixed",
        "text": "Chart crosshair + animation customization"
      },
      {
        "kind": "fixed",
        "text": "Chart polish + ThemeToggle icon sizing"
      },
      {
        "kind": "fixed",
        "text": "Animation + layout polish (V2-READINESS)"
      },
      {
        "kind": "fixed",
        "text": "De-brand and production hardening"
      },
      {
        "kind": "fixed",
        "text": "KanbanCard gains a full action menu (Edit, Duplicate, Export,"
      },
      {
        "kind": "fixed",
        "text": "StepperPanel animation is now driven by motion tokens (--facet-motion-duration-base / --facet-motion-ease-standard) instead of a hardcoded 250ms ease-out. This is the first consumption of the @fuso..."
      }
    ]
  },
  {
    "version": "1.12.0",
    "date": "2026-08-27",
    "tag": "release",
    "changes": [
      {
        "kind": "added",
        "text": "WizardFormPage - react-hook-form + zod + Stepper orchestration"
      },
      {
        "kind": "added",
        "text": "DateRangePicker - single-date and range modes with quick presets"
      },
      {
        "kind": "added",
        "text": "Chart - dependency-free line / bar / area chart in pure SVG"
      },
      {
        "kind": "added",
        "text": "EmptyStatePage - full-page empty state with CTA + illustration slot"
      },
      {
        "kind": "added",
        "text": "QrScanner - browser getUserMedia QR / barcode scanner"
      },
      {
        "kind": "added",
        "text": "ConsentCapture - scroll-to-accept legal consent + signature pad"
      },
      {
        "kind": "added",
        "text": "PricingComparison - mobile-friendly tier cards + feature matrix"
      },
      {
        "kind": "added",
        "text": "Tree - collapsible nested list with selection + keyboard nav"
      },
      {
        "kind": "added",
        "text": "MultiCombobox - multi-select chips with search + keyboard nav"
      },
      {
        "kind": "added",
        "text": "TagInput - free-form tag/chip input with separator / paste handling"
      },
      {
        "kind": "added",
        "text": "RangeSlider - two-thumb range slider with active-track highlight"
      },
      {
        "kind": "added",
        "text": "RatingInput - 5-star / N-item rating with half-star + keyboard"
      },
      {
        "kind": "added",
        "text": "CookieBanner - top-bar cookie notice with accept / reject / manage"
      },
      {
        "kind": "added",
        "text": "OtpInput - standalone OTP input with auto-advance + paste"
      },
      {
        "kind": "added",
        "text": "RichTextEditor - lightweight contenteditable + toolbar"
      },
      {
        "kind": "added",
        "text": "PhoneInput - country-code dropdown + E.164 formatting"
      },
      {
        "kind": "added",
        "text": "MentionInput - @mention autocomplete with paste handling"
      },
      {
        "kind": "added",
        "text": "ShineBorderCard - card with animated border shine"
      },
      {
        "kind": "added",
        "text": "GlowBorderCard - card with pulsing border glow"
      },
      {
        "kind": "added",
        "text": "PasswordStrengthMeter - standalone strength meter"
      },
      {
        "kind": "added",
        "text": "KanbanCard action menu (edit / duplicate / export / delete)"
      },
      {
        "kind": "fixed",
        "text": "Chart hover now tracks the nearest series"
      },
      {
        "kind": "fixed",
        "text": "Navbar hover dropdowns no longer blink"
      }
    ]
  },
  {
    "version": "1.11.0",
    "date": "2026-08-26",
    "tag": "release",
    "changes": [
      {
        "kind": "added",
        "text": "Stepper primitive (headless useStepper + StepperNav / StepperPanel / StepperFooter)"
      },
      {
        "kind": "added",
        "text": "KanbanBoard with native HTML5 drag-and-drop, move/add/remove cards"
      },
      {
        "kind": "added",
        "text": "ChangelogList with filter chips and kind-grouped bullets"
      },
      {
        "kind": "fixed",
        "text": "SignIn mfa_challenge wired to MfaVerifyForm"
      }
    ]
  },
  {
    "version": "1.10.0",
    "date": "2026-08-18",
    "tag": "release",
    "changes": [
      {
        "kind": "added",
        "text": "AccountSettingsPanel nav + section content"
      },
      {
        "kind": "added",
        "text": "SecuritySectionCard grid"
      },
      {
        "kind": "added",
        "text": "ActivityFeed + StatCard + PageHeader for console surfaces"
      },
      {
        "kind": "changed",
        "text": "NotFound component gains gradient animation variant"
      }
    ]
  },
  {
    "version": "1.4.0",
    "date": "2026-08-12",
    "tag": "release",
    "changes": [
      {
        "kind": "added",
        "text": "FaqSection component"
      },
      {
        "kind": "added",
        "text": "IconRegistry (IconProvider / Icon / registerIcon)"
      },
      {
        "kind": "fixed",
        "text": "Billing interval toggle now honors the active state"
      },
      {
        "kind": "removed",
        "text": "Storybook + 48 story fixtures (replaced by docs inventory drift gate)"
      }
    ]
  }
];

