// AUTO-GENERATED by scripts/gen-changelog.mjs — do not edit.
// Regenerate with: pnpm gen:changelog
//
// Historical entries are curated in the generator. Pending entries are
// generated from .changeset/*.md files.

import type { ChangelogRelease } from "@fusorb/facet-components";

export const changelog: ChangelogRelease[] = [
  {
    version: "Unreleased",
    date: "Unreleased",
    tag: "feat",
    title: "Animation flexibility pass - remove hardcoded values from the animation surfaces.",
    pre: true,
    changes: [
      {
        kind: "added",
        text: "`dist/palettes/`, and exported from the package).",
      },
      {
        kind: "fixed",
        text: "**New tokens**: `--accent-fuchsia` (third stop of the brand gradient used by",
      },
      {
        kind: "fixed",
        text: "**Components**: the animation components (`card-animations`, `micro-interactions`,",
      },
      {
        kind: "fixed",
        text: "**Fix**: `RevealCard` / `ScrollReveal` interpolated `resolveEasing(\"standard\")`",
      },
      {
        kind: "fixed",
        text: "`--animate-facet-{marquee,aurora,beam}` now resolve their durations and",
      },
      {
        kind: "fixed",
        text: "**facet-motion**: Added an extensible driver registry (`registerDriver`,",
      },
      {
        kind: "fixed",
        text: "**facet-native**: The native driver (`facetDriver`) is now auto-registered",
      },
      {
        kind: "fixed",
        text: "**facet-cli**: Added `@fusorb/facet-motion`, `@fusorb/facet-native`,",
      },
      {
        kind: "fixed",
        text: "**check-boundaries**: Updated `@fusorb/facet-native` allowed-dependency set",
      },
      {
        kind: "fixed",
        text: "Overlay exit animations: drop the JS wrapper so the CSS exit actually runs.",
      },
      {
        kind: "fixed",
        text: "**Overlay lifecycle revert**: reverted dialog, sheet, drawer, alert-dialog,",
      },
      {
        kind: "fixed",
        text: "**Removed dead code**: deleted `src/ui/motion-usage.tsx` (`OverlayContext` +",
      },
      {
        kind: "fixed",
        text: "**Focus restore**: restored visible, keyboard-only focus rings on Button,",
      },
      {
        kind: "fixed",
        text: "**z-index normalization**: modal backdrops are now `z-[60]` (below their",
      },
      {
        kind: "fixed",
        text: "**Tests**: added `focus-ring.test.tsx` asserting the `focus-visible:` ring",
      },
    ],
  },
  {
    version: "1.2.2, 1.2.3, 1.3.1, 1.3.2, 1.4.2, 1.4.7, 1.5.1, 1.5.2, 2.0.2",
    date: "2026-10-06",
    tag: "fix",
    title: "v1.2.2, 1.2.3, 1.3.1, 1.3.2, 1.4.2, 1.4.7, 1.5.1, 1.5.2, 2.0.2",
    changes: [
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/3920b90",
      },
      {
        kind: "changed",
        text: "Updated dependencies []\\n- @fusorb/facet-components@2.0.2",
        href: "https://github.com/fusorb/facet/commit/ba81b34",
      },
      {
        kind: "changed",
        text: "@fusorb/facet-components@2.0.1",
      },
      {
        kind: "changed",
        text: "Swap ShineButton for the shared AnimatedButton component on auth form submit buttons (forgot-password, magic-link, MFA recovery, MFA verify) for visual consistency across the form suite.",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Phase 0 security fix: warn developers when `defaultStorage` (localStorage) is used for tokens, surface the XSS risk prominently, and add an optional `persist` adapter so consumers can plug in a cookie-backed strategy.",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Add an ESM `\"use client\"` banner to the `dist` builds of `@fusorb/facet-components`,\\n- `@fusorb/facet-auth`, and `@fusorb/facet-layout`.",
        href: "https://github.com/fusorb/facet/commit/cfabae9",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/1bf5de5",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/b1da261",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/1bf5de5",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/1bf5de5",
      },
      {
        kind: "changed",
        text: "Updated dependencies []\\n- @fusorb/facet-components@1.11.0\\n- @fusorb/facet-sdk@1.2.0",
        href: "https://github.com/fusorb/facet/commit/cfabae9",
      },
      {
        kind: "changed",
        text: "Updated dependencies []\\n- @fusorb/facet-components@1.10.0",
        href: "https://github.com/fusorb/facet/commit/b7accc3",
      },
      {
        kind: "changed",
        text: "Animation flexibility pass - remove hardcoded values from the animation surfaces.",
        href: "https://github.com/fusorb/facet/commit/3920b90",
      },
      {
        kind: "changed",
        text: "Stage 3 of the component-library cleanup:",
        href: "https://github.com/fusorb/facet/commit/ba81b34",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/3920b90",
      },
      {
        kind: "changed",
        text: "Updated dependencies []\\n- @fusorb/facet-tokens@1.3.0\\n- @fusorb/facet-motion@1.1.0",
        href: "https://github.com/fusorb/facet/commit/ba81b34",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/3920b90",
      },
      {
        kind: "changed",
        text: "Updated dependencies []\\n- @fusorb/facet-tokens@1.3.0\\n- @fusorb/facet-components@2.0.2\\n- @fusorb/facet-auth@1.3.2\\n- @fusorb/facet-layout@1.5.2",
        href: "https://github.com/fusorb/facet/commit/ba81b34",
      },
      {
        kind: "changed",
        text: "@fusorb/facet-components@2.0.1\\n- @fusorb/facet-auth@1.3.1\\n- @fusorb/facet-layout@1.5.1",
      },
      {
        kind: "changed",
        text: "Remove the collapsible/vertical-collapsible docs gallery variants for Resizable (were never wired to the variants.tsx list, leaving dead code in previews.tsx and usage.ts). Make the horizontal variant as polished as the vertical by adding the same height constraint and proper border separation.",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/1bf5de5",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/b1da261",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/1bf5de5",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/1bf5de5",
      },
      {
        kind: "changed",
        text: "Updated dependencies []\\n- @fusorb/facet-auth@1.2.3\\n- @fusorb/facet-components@1.11.0\\n- @fusorb/facet-sdk@1.2.0\\n- @fusorb/facet-layout@1.4.2",
        href: "https://github.com/fusorb/facet/commit/cfabae9",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/3920b90",
      },
      {
        kind: "changed",
        text: "Updated dependencies []\\n- @fusorb/facet-components@2.0.2\\n- @fusorb/facet-auth@1.3.2",
        href: "https://github.com/fusorb/facet/commit/ba81b34",
      },
      {
        kind: "changed",
        text: "@fusorb/facet-components@2.0.1\\n- @fusorb/facet-auth@1.3.1",
      },
      {
        kind: "changed",
        text: "Fix sidebar accordion (singleOpen) collapse, auto-infer ResizableHandle orientation, and export brand icons from the components barrel.",
        href: "https://github.com/fusorb/facet/commit/1bf5de5",
      },
      {
        kind: "changed",
        text: "Add an ESM `\"use client\"` banner to the `dist` builds of `@fusorb/facet-components`,\\n- `@fusorb/facet-auth`, and `@fusorb/facet-layout`.",
        href: "https://github.com/fusorb/facet/commit/cfabae9",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/1bf5de5",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/b1da261",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/205d83b",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/1bf5de5",
      },
      {
        kind: "changed",
        text: "Updated dependencies []",
        href: "https://github.com/fusorb/facet/commit/1bf5de5",
      },
      {
        kind: "changed",
        text: "Updated dependencies []\\n- @fusorb/facet-auth@1.2.3\\n- @fusorb/facet-components@1.11.0",
        href: "https://github.com/fusorb/facet/commit/cfabae9",
      },
    ],
  },
  {
    version: "1.1.2",
    date: "2026-09-27",
    tag: "fix",
    title: "v1.1.2",
    changes: [
      {
        kind: "changed",
        text: "Updated dependencies\\n- @fusorb/facet-components@1.4.0",
      },
      {
        kind: "changed",
        text: "De-brand and production hardening:",
        href: "https://github.com/fusorb/facet/commit/db287b3",
      },
    ],
  },
  {
    version: "1.0.1, 2.0.1",
    date: "2026-09-26",
    tag: "fix",
    title: "v1.0.1, 2.0.1",
    changes: [
      {
        kind: "changed",
        text: "Updated dependencies []\\n- @fusorb/facet-motion@1.0.1",
        href: "https://github.com/fusorb/facet/commit/e0b3053",
      },
      {
        kind: "changed",
        text: "## motion: fix first-frame delta causing spring animations to snap",
        href: "https://github.com/fusorb/facet/commit/e0b3053",
      },
    ],
  },
  {
    version: "0.1.0, 1.2.1",
    date: "2026-09-23",
    tag: "fix",
    title: "v0.1.0, 1.2.1",
    changes: [
      {
        kind: "changed",
        text: "Updated dependencies\\n- @fusorb/facet-components@1.4.0\\n- @fusorb/facet-auth@1.1.2",
      },
      {
        kind: "changed",
        text: "De-brand and production hardening:",
        href: "https://github.com/fusorb/facet/commit/db287b3",
      },
      {
        kind: "changed",
        text: "feat(store): extract SovGrant Zustand auth/tenant stores into @fusorb/facet-store",
        href: "https://github.com/fusorb/facet/commit/b7accc3",
      },
    ],
  },
  {
    version: "1.0.0",
    date: "2026-09-20",
    tag: "fix",
    title: "v1.0.0",
    changes: [
      {
        kind: "changed",
        text: "initial publish...",
        href: "https://github.com/fusorb/facet/commit/e79cbd5",
      },
      {
        kind: "changed",
        text: "Updated dependencies []\\n- @fusorb/facet-sdk@1.0.0\\n- @fusorb/facet-components@1.0.0",
        href: "https://github.com/fusorb/facet/commit/e79cbd5",
      },
      {
        kind: "changed",
        text: "initial publish...",
        href: "https://github.com/fusorb/facet/commit/e79cbd5",
      },
      {
        kind: "changed",
        text: "Updated dependencies []\\n- @fusorb/facet-tokens@1.0.0",
        href: "https://github.com/fusorb/facet/commit/e79cbd5",
      },
      {
        kind: "changed",
        text: "initial publish...",
        href: "https://github.com/fusorb/facet/commit/e79cbd5",
      },
      {
        kind: "changed",
        text: "initial publish...",
        href: "https://github.com/fusorb/facet/commit/e79cbd5",
      },
    ],
  },
];
