// AUTO-GENERATED by scripts/gen-site-data.mjs, do not edit by hand.
// Regenerate with: node scripts/gen-site-data.mjs
//
// Every package version and stat on the landing page comes from this file,
// resolved from the real workspace packages at generation time.

import type { IconName } from "@fusorb/facet-components";

export interface SitePackage {
  name: string;
  desc: string;
  version: string;
  icon: IconName;
}

export const SITE_PACKAGES: SitePackage[] = [
  {
    "name": "@fusorb/facet-components",
    "desc": "Radix-based UI component library: 114 accessible, styled components using the Alpha Palette design tokens",
    "version": "1.11.0",
    "icon": "boxes"
  },
  {
    "name": "@fusorb/facet-docs",
    "desc": "Installable, config-driven documentation site engine: component gallery with variant pages, per-variant usage tabs, install tabs, and an optional ecosystem links section. Mount <DocsApp config={...} /> with your own brand, pages, and nav.",
    "version": "1.4.7",
    "icon": "book-open"
  },
  {
    "name": "@fusorb/facet-auth",
    "desc": "Domain-customizable auth components: ArcProvider, SignIn/SignUp, Guard, MfaDialog, and 5 domain presets (fintech, med, edu, enterprise, default). Wired to @fusorb/facet-sdk.",
    "version": "1.2.3",
    "icon": "shield-check"
  },
  {
    "name": "@fusorb/facet-layout",
    "desc": "Domain-configurable app shell: Sidebar, Topbar, AuthLayout, ConsoleLayout, LandingLayout, PageHeader, TenantSwitcher, and 5 domain presets (fintech, med, edu, enterprise, default).",
    "version": "1.4.2",
    "icon": "building"
  },
  {
    "name": "@fusorb/facet-sdk",
    "desc": "SovGrant API client: framework-agnostic fetch SDK. Auth, credentials, passkeys, OAuth, tenants, billing, webhooks, audit, IdP.",
    "version": "1.2.0",
    "icon": "zap"
  },
  {
    "name": "@fusorb/facet-tokens",
    "desc": "Design tokens: Alpha Palette colors, typography, spacing, surfaces, and sub-brand accents in OKLCH, as CSS variables and a Tailwind v4 theme.",
    "version": "1.1.4",
    "icon": "palette"
  },
  {
    "name": "@fusorb/facet-emails",
    "desc": "Framework-agnostic email template renderer: render React or plain template trees to email-safe HTML and text, with template primitives and a dev preview server. Zero runtime dependencies.",
    "version": "1.1.1",
    "icon": "mail"
  },
  {
    "name": "@fusorb/facet-cli",
    "desc": "facet CLI: scaffold docs + email template sites, add components, generate tree-shaken icon registries, and audit/update your facet setup from the terminal.",
    "version": "1.0.0",
    "icon": "terminal"
  },
  {
    "name": "@fusorb/facet-store",
    "desc": "Framework-agnostic state stores for SovGrant auth: Zustand session + tenant state, token-refresh wiring, and hooks consumable across web and React Native. No React coupling in the store logic itself; consumers bring their own React for the auto-generated hooks.",
    "version": "1.0.0",
    "icon": "store"
  },
  {
    "name": "@fusorb/facet-motion",
    "desc": "Domain-customizable animation engine: generator-driven core (tween + spring), observable motion values, CSS driver with prefers-reduced-motion, a 15-family generative registry, and thin React bindings. Wired to @fusorb/facet-tokens CSS custom properties.",
    "version": "0.1.0",
    "icon": "sparkle"
  },
  {
    "name": "@fusorb/facet-native",
    "desc": "React Native motion driver for @fusorb/facet-motion - subscribes facet motion values to a consumer-provided Animated module (react-native or reanimated v2) via bindAnimated().",
    "version": "0.1.0",
    "icon": "phone"
  },
  {
    "name": "@fusorb/facet-sandbox",
    "desc": "Framework-agnostic live-preview sandbox host: block registry, adapter seam, security helpers. Ships no framework code; the React adapter ships under /react.",
    "version": "1.0.0",
    "icon": "play"
  },
  {
    "name": "@fusorb/facet-utils",
    "desc": "Shared styling utilities for Facet packages (cn).",
    "version": "0.1.0",
    "icon": "package"
  }
];

export interface SiteStat {
  value: string;
  label: string;
}

export const SITE_STATS: SiteStat[] = [
  {
    "value": "116",
    "label": "components"
  },
  {
    "value": "10",
    "label": "API SDKs"
  },
  {
    "value": "5",
    "label": "layout shells"
  },
  {
    "value": "5",
    "label": "auth presets"
  },
  {
    "value": "1190",
    "label": "icons"
  }
];

/** Total number of workspace packages (auto-detected from the packages directory). */
export const SITE_PACKAGES_COUNT: number = 13;

/** Number of component files in packages/components (auto-detected). */
export const COMPONENT_COUNT: number = 116;

/** Number of registered icons (auto-detected from icon-map.ts). */
export const ICON_COUNT: number = 1190;

// Root workspace version, resolved from the repo package.json at generation
// time.  Consumers: HeroSection version badge, changelog, etc.
export const SITE_VERSION: string = "2.0.0";
