// AUTO-GENERATED by scripts/gen-site-data.mjs, do not edit by hand.
// Regenerate with: node scripts/gen-site-data.mjs
//
// Every package version and stat on the landing page comes from this file,
// resolved from the real workspace packages at generation time.

import type { IconName } from "@fusorb/facet-components";

export interface SitePackage {
  name: string;
  desc: string;
  version: string;
  icon: IconName;
}

export const SITE_PACKAGES: SitePackage[] = [
  {
    "name": "@fusorb/facet-components",
    "desc": "Accessible, styled React components built on Radix primitives.",
    "icon": "boxes",
    "version": "1.11.0"
  },
  {
    "name": "@fusorb/facet-docs",
    "desc": "Installable docs engine: mount <DocsApp> with your own brand, nav, and pages.",
    "icon": "book-open",
    "version": "1.4.7"
  },
  {
    "name": "@fusorb/facet-auth",
    "desc": "SignIn, SignUp, Guard, MFA and forms with per-domain presets.",
    "icon": "shield-check",
    "version": "1.2.3"
  },
  {
    "name": "@fusorb/facet-layout",
    "desc": "Console, auth and landing shells with a collapsible icon rail.",
    "icon": "building",
    "version": "1.4.2"
  },
  {
    "name": "@fusorb/facet-sdk",
    "desc": "Typed fetch client for SovGrant: domain SDKs, zero React.",
    "icon": "zap",
    "version": "1.2.0"
  },
  {
    "name": "@fusorb/facet-tokens",
    "desc": "Alpha Palette design tokens: color, type, spacing, surfaces.",
    "icon": "palette",
    "version": "1.1.4"
  },
  {
    "name": "@fusorb/facet-emails",
    "desc": "Framework-agnostic email templates: HTML/text from React or plain trees.",
    "icon": "mail",
    "version": "1.1.1"
  },
  {
    "name": "@fusorb/facet-cli",
    "desc": "Scaffold docs + emails, audit/update your facet setup, generate an icon registry.",
    "icon": "terminal",
    "version": "2.0.0"
  },
  {
    "name": "@fusorb/facet-store",
    "desc": "Framework-agnostic Zustand stores for SovGrant (session, tenant, token-refresh).",
    "icon": "store",
    "version": "2.0.0"
  }
];

export interface SiteStat {
  value: string;
  label: string;
}

export const SITE_STATS: SiteStat[] = [
  {
    "value": "114",
    "label": "components"
  },
  {
    "value": "10",
    "label": "API SDKs"
  },
  {
    "value": "3",
    "label": "layout shells"
  },
  {
    "value": "5",
    "label": "auth presets"
  }
];
